README.md, index.js, package.json
Using this, no processing is done when webpack 'debug' mode is used and the loader acts as a regular file-loader.
Use this to speed up initial and, to a lesser extent, subsequent compilations while developing or using webpack-dev-server. Normal builds are processed normally, outputting oprimized files.
=> Feature: Bypass processing when webpack is running on debug

README.md
Update README to fix the following error using file-loader in the Example section.
``` bash
ERROR in ./app/assets/png/brace.png
Module parse failed: /Users/stanleyn/Projects/stanleyhlng/knowledge/livereload-test/browser/node_modules/image-webpack-loader/index.js?bypassOnDebug!/Users/stanleyn/Projects/stanleyhlng/knowledge/livereload-test/browser/app/assets/png/brace.png Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
@ ./app/js/app.js 6:10-44
```
=> Updated the Example in the READMD.md

README.md
as mentioned in issue #7: https://github.com/tcoopman/image-webpack-loader/issues/7
=> update loader `image` to `image-webpack` in doc

index.js
Looks like adding optipng before pngquant prevents pngquant from ever getting called.
=> Actually use pngquant

README.md, index.js, package.json, test/webpack.config.js
Uses the loader util function `getLoaderConfig` (https://github.com/webpack/loader-utils#getloaderconfig) to get config, which loads from both the query string (backwards compatible) and from a config section named `imageWebpackLoader`. See test config for example usage.
Fixes https://github.com/tcoopman/image-webpack-loader/issues/30
=> Load config optionally from a section in webpack config

README.md
Loader configs seem to go outside the module section rather than in it
=> Fix configuration section section in README

.gitignore, CHANGELOG.md, README.md, index.js, package.json, test/webpack.config.js
Hi,
I experimented with mozjpeg and it looks like it produces much better results than jpegtran.
jpegtran:
```
f72836bbac59ca5e265a0fc7591dfd09.jpg  2.43 MB          [emitted]
```
Mozjpeg:
```
b47f5167a0c34fca03f17dc35df9358d.jpg  1.21 MB          [emitted]
```
I couldn't see much of a difference on 300% zoom when i was testing on quality 75, but i set the default quality to 80 anyway. Hope you like it, I sure do like those smaller images.
PS. Dont mind the whitespace diff, it's just something my editor does with trailing spaces.
=> Use mozjpeg instead of jpegtran

index.js
Related to [Pull Request #39](https://github.com/tcoopman/image-webpack-loader/pull/39).
Since we do have options for all optimizers now, we can specify the 'enabled' flag on optimizer level instead of loader level. Usage is simple aswell:
```
query: {
gifsicle: {
enabled: true,
interlaced: true,
optimizationLevel: 3,
number: 256
},
mozjpeg: {
enabled: true,
quality: 90,
progressive: true
},
optipng: {
enabled: true,
optimizationLevel: 7
},
pngquant: {
enabled: false
},
svgo: {
enabled: false
}
}
```
Defaults to true.
=> Allow enabling/disabling of individual optimizers

index.js
Interlaced & optimizationLevel will always take precedence
So if the config is:
```
interlaced: false,
optimizationLevel: 4,
gifsicle: {
enabled: false,
interlaced: true,
number: 256
},
optipng: {
enabled: false,
optimizationLevel: 7
}
```
It will use:
```
interlaced: false
optimizationLevel: 4
```
=> Backwards compatibility for interlaced and optimizationLevel + deprecated warnings

README.md
Due to a breaking change in Webpack 2, using a loader without '-loader' on the end causes webpack 2 (2.2.0-rc.3) to throw an error.
I simply changed the README example so it would not cause this error.
=> Changed README example

README.md
see https://github.com/tcoopman/image-webpack-loader/issues/51#issuecomment-273597313
=> Add libpng warning to install instructions

README.md
According to some benchmarks, the greedy versions run ~20% slower than the simple non-greedy version with a fairly shallow file path. This gets worse  when filepaths are more deeply nested. 
This ended up causing some slowness in my initial webpack builds, so I figure we can save a few users some headaches :)
=> Avoid using greedy regex in README examples

README.md
- change `query` object by `options` object (webpack2)
- options must be specified for each optimiser* (no more global options)
*🇬🇧 💪🏻
=> docs(readme): update webpack2 definition

index.js
After some merge problem on my previous PR, now webp is always enabled, instead of being optional.
Solves https://github.com/tcoopman/image-webpack-loader/issues/112
=> Fix webp merge problem

package.json
I noticed that svgo 1.0.0 compresses my svgs to a smaller size. Can we update this dependency? @tcoopman
=> Bump imagemin-svgo to v6.0.0 for svgo v1.0.0, better compression

README.md
Minor update to the readme to help clarify which optimisers are enabled by default.
=> Clarify which optimisers are enabled by default

README.md, index.js, package-lock.json, package.json
- Added `disable` option (updated readme as well)
**Why?** Basically just alternative to bypassOnDebug, because that option depends on webpack debug mode, which was deprecated in version 2 (https://stackoverflow.com/a/41779342). The new `disable` option doesn't. The `disable` option also seems to be the common way for other webpack loaders and plugins.
- Replaced `rm -rf` with rimraf
**Why?** Because rimraf is compatible with Windows, while `rm -rf` is not (at least not by default), this also caused test script to fail, but not with rimraf.
- Added package-lock.json
**Why?** It's automatically added by npm, from version 5 I think.
- Updated imagemin dependencies
**Why?** Why not?
=> Disable option (alternative to bypassOnDebug)

package.json
It's only used for tests! It's a very large dependency so it's nice to
not have to install it.
Thanks!
=> Move webpack-cli to devDependencies

package-lock.json, package.json
Chasing the error `pngquant pre-build test failed` on my CI system, I
found this library as trigger.
The real problem is with `pngquant-bin@4`. The latest version fix that.
This is update the dependency chain to include that fix `imagemin-pngquant` > `pngquant-bin`.
fix #161
relevant: imagemin/imagemin-pngquant@fcf28bb037b384d11cf8cfe5f8073b99ea9b9571
=> Update `imagemin-pngquant` version

package-lock.json, package.json
Upgraded imagemin-webp to `^5`, which resolves the memory exposure warning.
Upgraded Webpack CLI to latest as well which was causing issues due to https://github.com/webpack/webpack-cli/issues/607
Resolves #162
=> resolve npm@6 audit warnings

index.js, package-lock.json, package.json, schema.json
Added schema validations using [schema-utils](https://github.com/webpack/schema-utils).
Changed the default of `webp` to `{}` as per the docs.
**Additional Info**
@tcoopman there are few security alerts in two of the dependencies. Need your confirmation before fixing them
=> chore: added schema validations

README.md
See tcoopman/image-webpack-loader#262
Add instructions for container images:
- node:12-buster
- node:12-buster-slim
- node:12-alpine
Measure typical image pull and package installation times
for container images above.
Add recommendation according to build time and image size.
=> docs: add container installation manual

.github/workflows/codeql-analysis.yml, .github/workflows/testing.yml
Add two Github action pipelines:
- `CodeQl analysis`: A tool from Github to scan for security flaws
- `Test`: Run `npm test` against node 10 to 15
Both pipeline run on ubuntu-latest.
They are configured to run for every PR against `master` and every commits on master.
I did not remove travis config.
You can check actions on my fork https://github.com/Webeleon/image-webpack-loader/actions
close #260
=> Run test in github actions

index.js, package-lock.json, package.json
Related to https://github.com/tcoopman/image-webpack-loader/pull/412, this PR upgrades `imagemin-webp` from v6 to v7. Per the release notes, v7 changes it output format to ESM which necessitates the use of `import` instead of `require`, which can also be noted in the failing CI in the above linked PR from dependabot:
> Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/runner/work/image-webpack-loader/image-webpack-loader/node_modules/imagemin-webp/index.js
require() of ES modules is not supported.
After changing to `import`, the previously failing `npm run test` is now passing while using `imagemin-webp@7`.
This is required to upgrade/remove a transient dependency `trim-newlines` which currently has a "High" security vulnerability, causing Dependabot alerts across several …
=> chore: upgrade imagemin-webp to v7.0.0
